name: Skylite UX
description: Self-hosted family manager (Calendar, Todos, Shopping Lists)
version: 2026.2.3
slug: skylite_ux
url: https://github.com/Wetzel402/Skylite-UX
image: wetzel402/skylite-ux-ha
arch:
  - amd64
  - aarch64
panel_icon: mdi:calendar
panel_title: Skylite UX
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: Web UI port
map:
  - addon_config:rw
  - data:rw
webui: http://[HOST]:[PORT:3000]/
ingress: true
ingress_entry: /
ingress_port: 3000
options:
  data_location: /data
  TZ: America/Chicago
  log_level: info
  database: bundled
schema:
  data_location: str
  TZ: str
  log_level: list(debug|info|warn|error|verbose)
  database: list(bundled|external)
  DB_HOSTNAME: str?
  DB_PORT: int?
  DB_USERNAME: str?
  DB_PASSWORD: str?
  DB_DATABASE_NAME: str?
